spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?allowPublicKeyRetrieval=true&useSSL=false
    username: app_user
    password: app_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  packagesToScan: com.mercadolivro.controller
  pathsToMatch: "/**"

jwt:
  secret: mD4tT6+3rebPeHf2neGHT5IR+LnppxBPcGAi9T8RmavB80ObYEFBLXk64zQtUwg6khLb7WHJhWr9FcV4EjYrLQ==
  expiration: 3600000
